#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# ------------------------------------------------------------------------------
# Gradle start up script for POSIX generated by Gradle.
# ------------------------------------------------------------------------------

APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}

# Resolve the absolute path of the script.
APP_HOME=$( cd "${0%/*}" && pwd -P ) || exit

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

if [ ! -r "$CLASSPATH" ]; then
    echo "ERROR: Could not find $CLASSPATH." >&2
    echo >&2 "Please run this script from a project containing the Gradle Wrapper."
    exit 1
fi

# Determine the Java executable.
if [ -n "$JAVA_HOME" ] && [ -x "$JAVA_HOME/bin/java" ]; then
    JAVACMD="$JAVA_HOME/bin/java"
elif command -v java >/dev/null 2>&1; then
    JAVACMD=$(command -v java)
else
    echo "ERROR: JAVA_HOME is not set and no 'java' command could be found." >&2
    exit 1
fi

# Increase the maximum file descriptor limit where possible.
MAX_FD=maximum

if [ -z "$GRADLE_OPTS" ]; then
    GRADLE_OPTS=""
fi

# For compatibility with Gradle's standard wrapper.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

set -- \
    "$DEFAULT_JVM_OPTS" \
    "-Dorg.gradle.appname=$APP_BASE_NAME" \
    "-classpath" "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"

exec "$JAVACMD" "$@"
